# Generated by Django 3.1.1 on 2021-03-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='doenca',
            field=models.ManyToManyField(to='teste.Doenca'),
        ),
    ]
