# Generated by Django 3.1.1 on 2021-03-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_animal_doenca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='doenca',
            new_name='doencas',
        ),
        migrations.AddField(
            model_name='doenca',
            name='animais',
            field=models.ManyToManyField(to='teste.Animal'),
        ),
    ]
