# Generated by Django 3.1.1 on 2021-03-03 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0003_auto_20210302_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='doencas',
        ),
        migrations.RemoveField(
            model_name='doenca',
            name='animais',
        ),
    ]
