# Generated by Django 3.1.1 on 2021-03-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0004_auto_20210302_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobertura',
            old_name='inicio2',
            new_name='termino',
        ),
        migrations.RenameField(
            model_name='gravidez',
            old_name='inicio2',
            new_name='termino',
        ),
        migrations.AddField(
            model_name='cobertura',
            name='ativa',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gravidez',
            name='ativa',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
