# Generated by Django 3.1.1 on 2021-03-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0005_auto_20210317_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('motivo', models.TextField(max_length=500)),
                ('saida', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gravidez',
            name='termino',
        ),
    ]
