# Generated by Django 3.1.1 on 2021-03-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0006_auto_20210324_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cobertura',
        ),
    ]
