# Generated by Django 3.1.1 on 2021-04-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0007_delete_cobertura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gravidez',
        ),
    ]
